export interface Location {
  slug: string;
  name: string;
  area: string;
}

export const locations: Location[] = [
  { slug: "boring-road", name: "Boring Road", area: "Boring Road Patna" },
  { slug: "kankarbagh", name: "Kankarbagh", area: "Kankarbagh Patna" },
  { slug: "rajendra-nagar", name: "Rajendra Nagar", area: "Rajendra Nagar Patna" },
  { slug: "fraser-road", name: "Fraser Road", area: "Fraser Road Patna" },
  { slug: "bailey-road", name: "Bailey Road", area: "Bailey Road Patna" },
  { slug: "bhuthnath", name: "Bhuthnath", area: "Bhuthnath Patna" },
  { slug: "gola-road", name: "Gola Road", area: "Gola Road Patna" },
  { slug: "raja-bazar", name: "Raja Bazar", area: "Raja Bazar Patna" },
  { slug: "jagdev-path", name: "Jagdev Path", area: "Jagdev Path Patna" },
  { slug: "bariya-bus-stand", name: "Bariya Bus Stand", area: "Bariya Bus Stand Patna" },
  { slug: "mithapur", name: "Mithapur", area: "Mithapur Patna" },
  { slug: "danapur", name: "Danapur", area: "Danapur Patna" },
  { slug: "patna-junction", name: "Patna Junction", area: "Patna Junction" },
  { slug: "patliputra-station", name: "Patliputra Station", area: "Patliputra Station Patna" },
  { slug: "patliputra-colony", name: "Patliputra Colony", area: "Patliputra Colony Patna" },
  { slug: "dakbangla-chauraha", name: "Dakbangla Chauraha", area: "Dakbangla Chauraha Patna" },
  { slug: "exhibition-road", name: "Exhibition Road", area: "Exhibition Road Patna" },
  { slug: "gandhi-maidan", name: "Gandhi Maidan", area: "Gandhi Maidan Patna" },
  { slug: "jamal-road", name: "Jamal Road", area: "Jamal Road Patna" },
  { slug: "sri-krishna-puri", name: "Sri Krishna Puri", area: "Sri Krishna Puri Patna" },
  { slug: "ashok-rajpath", name: "Ashok Rajpath", area: "Ashok Rajpath Patna" },
  { slug: "anisabad", name: "Anisabad", area: "Anisabad Patna" },
  { slug: "phulwari-sharif", name: "Phulwari Sharif", area: "Phulwari Sharif Patna" },
  { slug: "khagaul", name: "Khagaul", area: "Khagaul Patna" },
  { slug: "saguna-more", name: "Saguna More", area: "Saguna More Patna" },
  { slug: "rukanpura", name: "Rukanpura", area: "Rukanpura Patna" },
  { slug: "jagdeo-path", name: "Jagdeo Path", area: "Jagdeo Path Patna" },
  { slug: "baily-road-canal-road", name: "Baily Road Canal Road", area: "Baily Road Canal Road Patna" },
  { slug: "transport-nagar", name: "Transport Nagar", area: "Transport Nagar Patna" },
  { slug: "sipara", name: "Sipara", area: "Sipara Patna" },
  { slug: "bihta", name: "Bihta", area: "Bihta Patna" },
  { slug: "naubatpur", name: "Naubatpur", area: "Naubatpur Patna" },
  { slug: "aiims-patna-area", name: "AIIMS Patna Area", area: "AIIMS Patna Area" },
  { slug: "digha", name: "Digha", area: "Digha Patna" },
  { slug: "kurji", name: "Kurji", area: "Kurji Patna" },
  { slug: "danapur-cantt", name: "Danapur Cantt", area: "Danapur Cantt Patna" },
  { slug: "didarganj", name: "Didarganj", area: "Didarganj Patna" },
  { slug: "fatuha", name: "Fatuha", area: "Fatuha Patna" },
  { slug: "sampatchak", name: "Sampatchak", area: "Sampatchak Patna" },
  { slug: "gaurichak", name: "Gaurichak", area: "Gaurichak Patna" },
  { slug: "hanuman-nagar", name: "Hanuman Nagar", area: "Hanuman Nagar Patna" },
  { slug: "lohianagar", name: "Lohianagar", area: "Lohianagar Patna" },
  { slug: "kadamkuan", name: "Kadamkuan", area: "Kadamkuan Patna" },
  { slug: "bakarganj", name: "Bakarganj", area: "Bakarganj Patna" },
  { slug: "rajiv-nagar", name: "Rajiv Nagar", area: "Rajiv Nagar Patna" },
  { slug: "indrapuri", name: "Indrapuri", area: "Indrapuri Patna" },
  { slug: "gardani-bagh", name: "Gardani Bagh", area: "Gardani Bagh Patna" },
  { slug: "shastri-nagar", name: "Shastri Nagar", area: "Shastri Nagar Patna" },
  { slug: "punaichak", name: "Punaichak", area: "Punaichak Patna" },
  { slug: "dakbunglow-road", name: "Dakbunglow Road", area: "Dakbunglow Road Patna" },
  { slug: "station-road", name: "Station Road", area: "Station Road Patna" },
  { slug: "meethapur", name: "Meethapur", area: "Meethapur Patna" },
  { slug: "karbigahiya", name: "Karbigahiya", area: "Karbigahiya Patna" },
  { slug: "chitkohra", name: "Chitkohra", area: "Chitkohra Patna" },
  { slug: "mithapur-bus-stand", name: "Mithapur Bus Stand", area: "Mithapur Bus Stand Patna" },
  { slug: "sabzibagh", name: "Sabzibagh", area: "Sabzibagh Patna" },
  { slug: "muradpur", name: "Muradpur", area: "Muradpur Patna" },
];

export function getLocation(slug: string): Location | undefined {
  return locations.find((l) => l.slug === slug);
}
